kind: pipeline
name: default
type: docker
steps:
  - name: Build
    image: golang
    commands:
      - go vet ./...
      - /bin/sh build_x86_64.sh

  - name: Build Docker Image
    image: library/docker
    commands:
      - docker build -t intelite-mqtt:latest .
      - docker stop intelite-mqtt || true
      - docker container rm intelite-mqtt || true
      - docker run -d -v /volume1/public/NAS/intelite-mqtt:/data --restart=always --name intelite-mqtt intelite-mqtt:latest
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    when:
      branch: [main]


volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock